# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: CI010.XMinecraftLauncher
PackageVersion: 0.37.5.625
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.14316.0
InstallerType: msix
PackageFamilyName: XMCL_68mcaawk44tpj
Installers:
- Architecture: x64
  InstallerUrl: https://xmcl-release-ms.azureedge.net/releases/xmcl-0.37.6.appx
  InstallerSha256: 7E56533701D3AA579CD6AEFB25DF1B5919B158D5AA6A0B6E8462251BE58A5C16
  SignatureSha256: 2E0A5467C867FC915A961C79F9ABD251553AE2D5142279CAAA4E0C517528C09D
ManifestType: installer
ManifestVersion: 1.5.0
