# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: CI010.XMinecraftLauncher
PackageVersion: 0.35.1.0
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.14316.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://xmcl-release-ms.azureedge.net/releases/xmcl-0.35.1.appx
  InstallerSha256: 5D440793CE4E4CA0B8C63AC97593BACF65C42A924495B5F7F46B8500467E15A9
  SignatureSha256: 75B374EA3EAA55C129A70866C1A82BC54BCA9C8F32CBAF29371A09303BF2843B
  PackageFamilyName: XMCL_68mcaawk44tpj
ManifestType: installer
ManifestVersion: 1.4.0
